"use client";

import { useEffect, useMemo, useState } from "react";
import type { StageTwoAnalysisSnapshot } from "@/lib/biomechanics/stage-two-analysis";
import {
  parseStageThreeRules,
  type StageThreeReviewFlag,
  type StageThreeRule,
  type StageThreeSeverity,
} from "@/lib/biomechanics/stage-three-review";
import type { MovementType } from "@/lib/pose/types";

export function StageThreeReviewPanel({
  movement,
  analysis,
  rules,
  flags,
  onRulesChange,
  onClearFlags,
}: {
  movement: MovementType;
  analysis: StageTwoAnalysisSnapshot | null;
  rules: readonly StageThreeRule[];
  flags: readonly StageThreeReviewFlag[];
  onRulesChange: (rules: StageThreeRule[]) => void;
  onClearFlags: () => void;
}) {
  const [configuration, setConfiguration] = useState("[]");
  const [configurationError, setConfigurationError] = useState<string | null>(null);
  const [configurationMessage, setConfigurationMessage] = useState<string | null>(null);

  useEffect(() => {
    setConfiguration(JSON.stringify(rules, null, 2));
  }, [rules]);

  const movementRules = useMemo(
    () => rules.filter((rule) => rule.movement === movement),
    [movement, rules],
  );
  const movementFlags = useMemo(
    () => flags.filter((flag) => flag.movement === movement).slice().reverse(),
    [flags, movement],
  );
  const highestSeverity = highestSeverityOf(movementFlags);

  function applyConfiguration() {
    setConfigurationError(null);
    setConfigurationMessage(null);
    try {
      const parsedJson = JSON.parse(configuration) as unknown;
      const parsedRules = parseStageThreeRules(parsedJson);
      onRulesChange(parsedRules);
      setConfigurationMessage(
        parsedRules.length
          ? `${parsedRules.length} reviewed rule${parsedRules.length === 1 ? "" : "s"} loaded for this browser session.`
          : "Stage 3 rules cleared. No review flags will be generated.",
      );
    } catch (error) {
      setConfigurationError(error instanceof Error ? error.message : "Could not parse Stage 3 rules.");
    }
  }

  function clearRules() {
    setConfiguration("[]");
    setConfigurationError(null);
    setConfigurationMessage("Rules cleared. Apply the empty configuration to disable Stage 3 flagging.");
  }

  return (
    <section className="overflow-hidden border border-zinc-300 bg-white shadow-[0_18px_60px_rgba(24,24,27,0.06)]">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-zinc-200 bg-[#241f17] px-5 py-4 text-white sm:px-6">
        <div>
          <p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-amber-300/85">
            Stage 3 · Clinician review flags
          </p>
          <h2 className="mt-1 text-lg font-semibold tracking-tight">
            Protocol-defined threshold exceedances
          </h2>
        </div>
        <div className="border border-white/15 bg-white/[0.04] px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-white/70">
          Review indicator · not injury prediction
        </div>
      </div>

      <div className="grid gap-px bg-zinc-200 sm:grid-cols-2 xl:grid-cols-4">
        <SummaryMetric
          label="Reviewed rules"
          value={String(movementRules.length)}
          detail={
            movementRules.length
              ? `Rules currently scoped to ${analysis?.movementLabel ?? movement}.`
              : "No thresholds are enabled by default."
          }
        />
        <SummaryMetric
          label="Session flags"
          value={String(movementFlags.length)}
          detail="Nearby frame crossings are reduced to the larger exceedance to avoid event spam."
        />
        <SummaryMetric
          label="Highest review tier"
          value={highestSeverity ? severityLabel(highestSeverity) : "None"}
          detail="Severity comes from the reviewed protocol; it is not generated by an injury model."
        />
        <SummaryMetric
          label="Program changes"
          value="Disabled"
          detail="Stage 3 never changes an exercise prescription or patient program automatically."
        />
      </div>

      <div className="grid gap-px bg-zinc-200 xl:grid-cols-[minmax(0,1.2fr)_minmax(380px,.8fr)]">
        <div className="bg-white">
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-200 px-5 py-4 sm:px-6">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-zinc-500">
                Review queue
              </p>
              <h3 className="mt-1 text-base font-semibold text-zinc-950">
                Timestamped movement indicators
              </h3>
            </div>
            <button
              type="button"
              onClick={onClearFlags}
              disabled={!movementFlags.length}
              className="border border-zinc-300 bg-white px-3 py-2 text-xs font-semibold text-zinc-700 disabled:cursor-not-allowed disabled:opacity-40"
            >
              Clear session flags
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full min-w-[900px] border-collapse text-left text-xs">
              <thead className="bg-zinc-50 text-zinc-500">
                <tr>
                  <th className="px-5 py-3 font-semibold">Tier</th>
                  <th className="px-4 py-3 font-semibold">Time</th>
                  <th className="px-4 py-3 font-semibold">Scope</th>
                  <th className="px-4 py-3 font-semibold">Indicator</th>
                  <th className="px-4 py-3 font-semibold">Observed</th>
                  <th className="px-4 py-3 font-semibold">Exceeded by</th>
                  <th className="px-4 py-3 font-semibold">Protocol</th>
                  <th className="px-4 py-3 font-semibold">Source</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-100 text-zinc-700">
                {movementFlags.length ? (
                  movementFlags.slice(0, 40).map((flag) => (
                    <tr key={flag.id}>
                      <td className="px-5 py-3"><SeverityBadge severity={flag.severity} /></td>
                      <td className="px-4 py-3 tabular-nums">{formatTimestamp(flag.timestampMs)}</td>
                      <td className="px-4 py-3">
                        {flag.scope === "rep" ? `Rep ${flag.repIndex ?? "—"}` : "Frame"}
                      </td>
                      <td className="px-4 py-3 font-medium text-zinc-950">{flag.label}</td>
                      <td className="px-4 py-3 tabular-nums">{formatValue(flag.measuredValue, flag.unit)}</td>
                      <td className="px-4 py-3 tabular-nums">{formatValue(flag.excess, flag.unit)}</td>
                      <td className="px-4 py-3">{flag.protocolId}</td>
                      <td className="px-4 py-3">
                        <a
                          href={flag.sourceUrl}
                          target="_blank"
                          rel="noreferrer"
                          className="font-medium text-sky-700 underline decoration-sky-300 underline-offset-2"
                        >
                          {flag.sourceLabel}
                        </a>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={8} className="px-5 py-10 text-center text-sm text-zinc-500">
                      {movementRules.length
                        ? "No configured thresholds have been exceeded in the current captured measurements."
                        : "Load a reviewed protocol to enable Stage 3 movement-review flags."}
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {movementFlags.length > 40 && (
            <div className="border-t border-zinc-200 bg-zinc-50 px-5 py-3 text-xs text-zinc-500 sm:px-6">
              Showing the 40 most recent flags. The in-memory session buffer is capped separately.
            </div>
          )}
        </div>

        <aside className="bg-[#f7f5f0] p-5 sm:p-6">
          <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-zinc-500">
            Reviewed protocol configuration
          </p>
          <h3 className="mt-2 text-base font-semibold text-zinc-950">Load sourced threshold rules</h3>
          <p className="mt-2 text-sm leading-6 text-zinc-600">
            Stage 3 deliberately contains no built-in “safe” or “risky” angle ranges. Paste a JSON array from a clinician-reviewed or study-approved protocol. Rules must identify the exercise, metric, source measurement method, source URL, reviewer, and review date.
          </p>

          <textarea
            aria-label="Stage 3 rule JSON"
            value={configuration}
            onChange={(event) => setConfiguration(event.target.value)}
            spellCheck={false}
            className="mt-5 min-h-[300px] w-full resize-y border border-zinc-300 bg-white p-3 font-mono text-[11px] leading-5 text-zinc-800 outline-none focus:border-zinc-700"
          />

          <div className="mt-3 flex flex-wrap gap-2">
            <button
              type="button"
              onClick={applyConfiguration}
              className="bg-zinc-950 px-4 py-2.5 text-xs font-semibold text-white"
            >
              Apply reviewed protocol
            </button>
            <button
              type="button"
              onClick={clearRules}
              className="border border-zinc-300 bg-white px-4 py-2.5 text-xs font-semibold text-zinc-700"
            >
              Prepare empty config
            </button>
          </div>

          {configurationError && (
            <div className="mt-4 border border-red-200 bg-red-50 p-3 text-xs leading-5 text-red-800">
              {configurationError}
            </div>
          )}
          {configurationMessage && !configurationError && (
            <div className="mt-4 border border-emerald-200 bg-emerald-50 p-3 text-xs leading-5 text-emerald-800">
              {configurationMessage}
            </div>
          )}

          <div className="mt-5 border-t border-zinc-300 pt-5 text-xs leading-5 text-zinc-600">
            <p className="font-semibold text-zinc-900">Supported rule scopes</p>
            <p className="mt-1">
              <span className="font-medium">Frame:</span> filtered Stage 2 angle/projection metrics. <span className="font-medium">Rep:</span> rep excursion, duration, or cadence after a completed supported movement cycle.
            </p>
            <p className="mt-3">
              A threshold crossing means only that a configured review rule was exceeded. It does not establish injury, future injury probability, diagnosis, or treatment need.
            </p>
          </div>
        </aside>
      </div>

      <div className="border-t border-zinc-200 bg-amber-50 px-5 py-4 text-xs leading-5 text-amber-950 sm:px-6">
        <span className="font-semibold">Stage 3 boundary:</span> flags are deterministic comparisons against externally supplied, reviewed protocol values. The patient program is never auto-adjusted. Clinician review remains required, and these flags must not be presented as a validated prediction of injury.
      </div>
    </section>
  );
}

function SummaryMetric({ label, value, detail }: { label: string; value: string; detail: string }) {
  return (
    <div className="min-h-[142px] bg-white p-5">
      <p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-zinc-500">{label}</p>
      <p className="mt-4 text-2xl font-semibold tracking-tight text-zinc-950 tabular-nums">{value}</p>
      <p className="mt-2 text-xs leading-5 text-zinc-500">{detail}</p>
    </div>
  );
}

function SeverityBadge({ severity }: { severity: StageThreeSeverity }) {
  const classes =
    severity === "high"
      ? "border-red-200 bg-red-50 text-red-800"
      : severity === "caution"
        ? "border-amber-200 bg-amber-50 text-amber-800"
        : "border-sky-200 bg-sky-50 text-sky-800";
  return (
    <span className={`inline-flex border px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] ${classes}`}>
      {severityLabel(severity)}
    </span>
  );
}

function highestSeverityOf(flags: readonly StageThreeReviewFlag[]): StageThreeSeverity | null {
  if (flags.some((flag) => flag.severity === "high")) return "high";
  if (flags.some((flag) => flag.severity === "caution")) return "caution";
  if (flags.some((flag) => flag.severity === "info")) return "info";
  return null;
}

function severityLabel(severity: StageThreeSeverity) {
  if (severity === "high") return "High review";
  if (severity === "caution") return "Caution";
  return "Info";
}

function formatTimestamp(timestampMs: number) {
  return `${(timestampMs / 1000).toFixed(2)} s`;
}

function formatValue(value: number, unit: StageThreeReviewFlag["unit"]) {
  if (unit === "deg") return `${value.toFixed(1)}°`;
  if (unit === "sec") return `${value.toFixed(2)} s`;
  return `${value.toFixed(1)} rpm`;
}
